# Generated by Django 4.2.4 on 2023-08-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20230811_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymodel",
            name="architecture_rating_value",
            field=models.CharField(blank=True, null=True, verbose_name="総合評定値(建築)"),
        ),
        migrations.AddField(
            model_name="companymodel",
            name="painting_rating_value",
            field=models.CharField(blank=True, null=True, verbose_name="総合評定値(塗装)"),
        ),
        migrations.AddField(
            model_name="companymodel",
            name="waterproof_rating_value",
            field=models.CharField(blank=True, null=True, verbose_name="総合評定値(防水)"),
        ),
        migrations.AlterField(
            model_name="companymodel",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="unionmodel",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="CompanyAchievementModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(choices=[("下請", "subcontractor"), ("元請", "prime contractor")], max_length=20),
                ),
                ("title", models.CharField(max_length=512)),
                ("content", models.TextField()),
                ("price", models.FloatField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.companymodel")),
            ],
            options={
                "verbose_name": "実績",
                "verbose_name_plural": "実績",
            },
        ),
    ]
