# Generated by Django 4.2.4 on 2023-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_companymodel_architecture_rating_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyachievementmodel",
            name="type",
            field=models.CharField(choices=[("sub_contractor", "下請"), ("prime_contractor", "元請")], max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(choices=[("union", "管理組合"), ("company", "施工会社")], max_length=20),
        ),
    ]
