# Generated by Django 4.2.4 on 2023-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ホームページ"),
        ),
    ]
