# Generated by Django 4.2.4 on 2023-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_unionmodel_building_alter_unionmodel_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyachievementmodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="companyachievementmodel",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
