# Generated by Django 4.2.4 on 2023-09-15 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_rename_create_at_companyachievementmodel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unionmodel",
            name="name",
        ),
    ]
