# Generated by Django 4.2.4 on 2023-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_companyachievementmodel_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyachievementmodel",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
