# Generated by Django 4.2.4 on 2023-09-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsatsu.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_companyachievementmodel_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=newsatsu.users.models.user_file_upload_directory_path)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
