# Generated by Django 4.2.4 on 2023-09-22 15:49

from django.db import migrations, models
import newsatsu.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_userfilemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyoverviewmodel",
            name="pr_image",
            field=models.FileField(
                blank=True, null=True, upload_to=newsatsu.users.models.pr_file_upload_directory_path
            ),
        ),
    ]
