# Generated by Django 4.2.4 on 2023-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_user_building_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyachievementmodel",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
