# Generated by Django 4.2.4 on 2023-10-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_companyachievementmodel_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertokenmodel",
            name="type",
            field=models.CharField(
                choices=[("create", "user create"), ("password", "reset password")], default="create", max_length=20
            ),
            preserve_default=False,
        ),
    ]
