# Generated by Django 4.2.4 on 2023-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_unionconstructionhistorymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verify",
            field=models.BooleanField(default=False, verbose_name="メール認証確認"),
        ),
    ]
