# Generated by Django 4.2.4 on 2023-10-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_alter_user_is_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_allow",
            field=models.BooleanField(default=False, verbose_name="利用承認"),
        ),
    ]
