# Generated by Django 4.2.4 on 2023-10-07 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_user_is_allow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfilemodel",
            options={"verbose_name": "提出書類", "verbose_name_plural": "提出書類"},
        ),
    ]
