# Generated by Django 4.2.4 on 2023-09-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notify", "0002_mailtypemodel_alter_notificationmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="notify_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="contenttypes.contenttype"
            ),
        ),
    ]
