# Generated by Django 4.2.4 on 2023-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0003_alter_notificationmodel_notify_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("date", models.DateField()),
                ("display_status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "最近の状況",
                "verbose_name_plural": "最近の状況",
            },
        ),
    ]
