# Generated by Django 4.2.4 on 2023-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0006_alter_mailtypemodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailtypemodel",
            options={"verbose_name": "メールテンプレート", "verbose_name_plural": "メールテンプレート"},
        ),
    ]
