# Generated by Django 4.2.4 on 2023-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0007_alter_mailtypemodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtypemodel",
            name="path",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
