# Generated by Django 4.2.4 on 2023-10-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0008_mailtypemodel_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationmodel",
            name="template_id",
        ),
        migrations.AddField(
            model_name="notificationmodel",
            name="template",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="notify.mailtypemodel"
            ),
        ),
    ]
