# Generated by Django 4.2.4 on 2023-08-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Construction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="工事名")),
                ("content", models.TextField(verbose_name="工事内容")),
                ("start_time", models.DateField(verbose_name="予定工期 ー 開始")),
                ("end_time", models.DateField(verbose_name="予定工期 ー 終了")),
                ("first_engineer", models.BooleanField(default=False, verbose_name="1級建築施工管理技士")),
                ("second_engineer", models.BooleanField(default=False, verbose_name="2級建築施工管理技士")),
                ("on_site_agent", models.BooleanField(default=False, verbose_name="現場代理人経験5年以上")),
                ("not_selected", models.BooleanField(default=False, verbose_name="指定しない")),
                ("request_QA", models.DateField(verbose_name="質疑受付予定")),
                ("end_QA", models.DateField(verbose_name="質疑回答予定")),
                ("quotation_request", models.DateField(verbose_name="見積もり提出締切")),
                ("company_request_number", models.IntegerField(verbose_name="要請会社数")),
                ("submit_document", models.TextField(verbose_name="提出書類")),
                ("site_insurance", models.BooleanField(blank=True, null=True, verbose_name="大規模修繕瑕疵保険加入")),
                ("guarantee_insurance", models.BooleanField(blank=True, null=True, verbose_name="履行保証保険加入")),
            ],
        ),
    ]
