# Generated by Django 4.2.4 on 2023-08-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_area_user_building_name_user_city_and_more"),
        ("constructions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="construction",
            options={"verbose_name": "工事", "verbose_name_plural": "工事"},
        ),
        migrations.AddField(
            model_name="construction",
            name="union",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.union"
            ),
        ),
    ]
