# Generated by Django 3.1.13 on 2023-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_rename_construction_constructionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmodel',
            name='status',
            field=models.CharField(choices=[('見積依頼', 'request Quotation'), ('質疑応答', 'question and answer'), ('入札', 'bidding'), ('ヒアリング会', 'hearing party'), ('採用', 'hiring'), ('入評価登録札', 'evaluation')], default='見積依頼', max_length=30),
        ),
        migrations.AlterField(
            model_name='constructionmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
