# Generated by Django 3.1.13 on 2023-08-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0004_auto_20230808_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionmodel',
            name='status',
        ),
    ]
