# Generated by Django 4.2.4 on 2023-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0006_constructionmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionmodel",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="constructionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("見積依頼", "request Quotation"),
                    ("質疑応答", "question and answer"),
                    ("入札", "bidding"),
                    ("ヒアリング会", "hearing party"),
                    ("採用", "hiring"),
                    ("入評価登録札", "evaluation"),
                ],
                max_length=30,
            ),
        ),
    ]
