# Generated by Django 4.2.4 on 2023-08-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_companymodel_id_alter_unionmodel_id_and_more"),
        ("constructions", "0008_alter_constructionmodel_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCompanyModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField(default=0)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("見積依頼中", "requesting"),
                            ("見積依頼", "accept request"),
                            ("見積辞退", "decline request"),
                            ("落選", "unsuccessful"),
                            ("質疑応答", "question and answer"),
                            ("入札", "bidding"),
                            ("ヒアリング会への招待中", "request hearing"),
                            ("ヒアリング会承認", "accept hearing"),
                            ("ヒアリング会へ拒否", "accept decline"),
                            ("採用中", "hiring"),
                            ("採用", "hired"),
                            ("採用落選", "unsuccessful hire"),
                            ("作業終了", "finished work"),
                            ("入評価登録札", "evaluation"),
                        ],
                        default="見積依頼中",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.companymodel"
                    ),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="constructions.constructionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "見積依頼会社",
                "verbose_name_plural": "見積依頼会社",
            },
        ),
    ]
