# Generated by Django 4.2.4 on 2023-08-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_companymodel_id_alter_unionmodel_id_and_more"),
        ("constructions", "0009_requestcompanymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestcompanymodel",
            name="construction",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RequestQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="質問")),
                (
                    "company",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.companymodel"
                    ),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問",
            },
        ),
        migrations.CreateModel(
            name="RequestAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=1024)),
                ("answer", models.TextField()),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "応答",
                "verbose_name_plural": "応答",
            },
        ),
    ]
