# Generated by Django 4.2.4 on 2023-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0010_alter_requestcompanymodel_construction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestcompanymodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("見積依頼中", "Requesting"),
                    ("見積依頼", "Request Accept"),
                    ("見積辞退", "Request Decline"),
                    ("落選", "Request Unsuccessful"),
                    ("質疑応答", "Qa"),
                    ("入札", "Bid"),
                    ("ヒアリング会への招待中", "Hearing Requesting"),
                    ("ヒアリング会承認", "Hearing Accept"),
                    ("ヒアリング会へ拒否", "Hearing Decline"),
                    ("採用中", "Hiring"),
                    ("採用", "Hired"),
                    ("採用落選", "Hiring Unsuccessful"),
                    ("作業終了", "Finished Work"),
                    ("入評価登録札", "Evaluation"),
                ],
                default="見積依頼中",
                max_length=20,
            ),
        ),
    ]
