# Generated by Django 3.1.13 on 2023-08-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230811_1858'),
        ('constructions', '0011_alter_requestcompanymodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companymodel')),
            ],
            options={
                'verbose_name': '入札会社',
                'verbose_name_plural': '入札会社',
            },
        ),
        migrations.CreateModel(
            name='HearingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ヒアリング会への招待中', 'Requesting'), ('ヒアリング会承認', 'Accept'), ('ヒアリング会へ拒否', 'Decline')], default='ヒアリング会への招待中', max_length=20)),
                ('location', models.CharField(max_length=30, verbose_name='住所')),
                ('start_time', models.DateTimeField(verbose_name='開始日')),
                ('contact_number', models.CharField(max_length=30, verbose_name='連絡番号')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companymodel')),
            ],
            options={
                'verbose_name': 'ヒアリング会',
                'verbose_name_plural': 'ヒアリング会',
            },
        ),
        migrations.CreateModel(
            name='HireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('採用中', 'Requesting'), ('採用承認', 'Accept'), ('採用辞退', 'Decline'), ('採用落選', 'Work Unsuccessful'), ('作業終了', 'Finished Work'), ('入評価登録札', 'Evaluation')], default='採用中', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companymodel')),
            ],
            options={
                'verbose_name': '採用',
                'verbose_name_plural': '採用',
            },
        ),
        migrations.CreateModel(
            name='RequestAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': '応答',
                'verbose_name_plural': '応答',
            },
        ),
        migrations.CreateModel(
            name='RequestQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='質問')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companymodel')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
            },
        ),
        migrations.RemoveField(
            model_name='requestquestion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='requestquestion',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='requestcompanymodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='requestcompanymodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='requestcompanymodel',
            name='message',
        ),
        migrations.AlterField(
            model_name='constructionmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='constructionmodel',
            name='status',
            field=models.CharField(choices=[('見積依頼', 'request Quotation'), ('質問', 'question'), ('応答', 'answer'), ('入札', 'bidding'), ('ヒアリング会', 'hearing party'), ('採用', 'hiring'), ('入評価登録札', 'evaluation')], default='見積依頼', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestcompanymodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestcompanymodel',
            name='status',
            field=models.CharField(choices=[('見積依頼中', 'Requesting'), ('見積依頼', 'Accept'), ('見積辞退', 'Decline'), ('落選', 'Request Unsuccessful')], default='見積依頼中', max_length=20),
        ),
        migrations.DeleteModel(
            name='RequestAnswer',
        ),
        migrations.DeleteModel(
            name='RequestQuestion',
        ),
        migrations.AddField(
            model_name='requestquestionmodel',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.constructionmodel'),
        ),
        migrations.AddField(
            model_name='requestanswermodel',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.constructionmodel'),
        ),
        migrations.AddField(
            model_name='hiremodel',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.constructionmodel'),
        ),
        migrations.AddField(
            model_name='hearingmodel',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.constructionmodel'),
        ),
    ]
