# Generated by Django 4.2.4 on 2023-09-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_unionmodel_building_alter_unionmodel_name_and_more"),
        ("constructions", "0015_constructionmodel_question_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidmodel",
            name="construction",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestanswermodel",
            name="company",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.companymodel"),
        ),
        migrations.AddField(
            model_name="requestcompanymodel",
            name="company",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.companymodel"),
        ),
        migrations.AlterUniqueTogether(
            name="bidmodel",
            unique_together={("company", "construction")},
        ),
        migrations.AlterUniqueTogether(
            name="hearingmodel",
            unique_together={("company", "construction")},
        ),
        migrations.AlterUniqueTogether(
            name="hiremodel",
            unique_together={("company", "construction")},
        ),
        migrations.AlterUniqueTogether(
            name="requestanswermodel",
            unique_together={("company", "construction")},
        ),
        migrations.AlterUniqueTogether(
            name="requestcompanymodel",
            unique_together={("company", "construction")},
        ),
        migrations.AlterUniqueTogether(
            name="requestquestionmodel",
            unique_together={("company", "construction")},
        ),
    ]
