# Generated by Django 4.2.4 on 2023-09-04 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0016_bidmodel_construction_requestanswermodel_company_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestanswermodel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="requestquestionmodel",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="requestanswermodel",
            name="company",
        ),
    ]
