# Generated by Django 4.2.4 on 2023-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0018_evaluationmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bidmodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="bidmodel",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="evaluationmodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="evaluationmodel",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="hearingmodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="hearingmodel",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="requestanswermodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="requestanswermodel",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="requestquestionmodel",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="requestquestionmodel",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
