# Generated by Django 4.2.4 on 2023-09-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_userfilemodel"),
        ("constructions", "0019_rename_create_at_bidmodel_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestQAModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="質問")),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.companymodel"
                    ),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問",
            },
        ),
        migrations.RemoveField(
            model_name="requestquestionmodel",
            name="company",
        ),
        migrations.RemoveField(
            model_name="requestquestionmodel",
            name="construction",
        ),
        migrations.DeleteModel(
            name="RequestAnswerModel",
        ),
        migrations.DeleteModel(
            name="RequestQuestionModel",
        ),
    ]
