# Generated by Django 4.2.4 on 2023-09-22 15:42

from django.db import migrations, models
import django.db.models.deletion
import newsatsu.constructions.models


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0020_requestqamodel_remove_requestquestionmodel_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionFileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(upload_to=newsatsu.constructions.models.construction_file_upload_directory_path),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="constructions.constructionmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidFileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=newsatsu.constructions.models.bid_file_upload_directory_path)),
                ("bid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="constructions.bidmodel")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
