# Generated by Django 4.2.4 on 2023-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("constructions", "0021_constructionfilemodel_bidfilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("request", "見積依頼"),
                    ("question", "質問"),
                    ("answer", "応答"),
                    ("bidding", "入札"),
                    ("hearing", "ヒアリング会"),
                    ("hiring", "採用"),
                    ("evaluation", "工事の評価"),
                ],
                default="request",
                max_length=30,
            ),
        ),
    ]
